SELECT
    ESIB.ITEM_NUMBER,
    ESIT.DESCRIPTION,
    IOP.ORGANIZATION_CODE,
    HOU.NAME,
    ITTT.TRANSACTION_TYPE_NAME,
    IMT.TRANSACTION_UOM,
    SUM(IMT.TRANSACTION_QUANTITY) TRANSACTION_QUANTITY,
    TRUNC(IMT.TRANSACTION_DATE, 'MM') TRANSACTION_DATE
FROM
    INV_MATERIAL_TXNS IMT,
    EGP_SYSTEM_ITEMS_B ESIB,
    EGP_SYSTEM_ITEMS_TL ESIT,
    INV_ORG_PARAMETERS IOP,
    HR_ORGANIZATION_UNITS_F_TL HOU,
    XLE_ENTITY_PROFILES XLE,
    INV_TRANSACTION_TYPES_B ITTB,
    INV_TRANSACTION_TYPES_TL ITTT
WHERE
    1 = 1
    AND (
        IMT.TRANSACTION_DATE BETWEEN NEW_TIME(TO_DATE(:p_fecha_ini, 'YYYY-MM-DD'), 'CST', 'GMT')
        AND NEW_TIME(TO_DATE(:p_fecha_fin, 'YYYY-MM-DD') + 0.99999, 'CST', 'GMT')
    )
    AND ESIB.INVENTORY_ITEM_ID = IMT.INVENTORY_ITEM_ID
    AND ESIB.ORGANIZATION_ID = IMT.ORGANIZATION_ID
    --AND ESIB.ITEM_NUMBER = 'MP1005'
    AND ESIT.INVENTORY_ITEM_ID = ESIB.INVENTORY_ITEM_ID
    AND ESIT.ORGANIZATION_ID = ESIB.ORGANIZATION_ID
    AND ESIT.LANGUAGE = 'E'
    AND XLE.LEGAL_ENTITY_IDENTIFIER = 'RTO840921RE4'
    AND IOP.LEGAL_ENTITY_ID = XLE.LEGAL_ENTITY_ID
    AND IOP.ORGANIZATION_CODE = 'TOKS0480'
    AND IOP.ORGANIZATION_ID = IMT.ORGANIZATION_ID
    AND HOU.ORGANIZATION_ID = IOP.ORGANIZATION_ID
    AND HOU.LANGUAGE = 'E'
    AND ITTB.TRANSACTION_TYPE_ID = IMT.TRANSACTION_TYPE_ID
    AND ITTT.TRANSACTION_TYPE_ID = ITTB.TRANSACTION_TYPE_ID
    AND ITTT.LANGUAGE = 'E'
    AND ITTT.TRANSACTION_TYPE_NAME IN(
        'Finalización de producto de trabajo en curso',
        'Recepción con orden de compra',
        'Recepción entre organizaciones de orden de transferencia',
        'Salida de material de trabajo en curso'
    )
GROUP BY
    ESIB.ITEM_NUMBER,
    ESIT.DESCRIPTION,
    IOP.ORGANIZATION_CODE,
    HOU.NAME,
    ITTT.TRANSACTION_TYPE_NAME,
    IMT.TRANSACTION_UOM,
    TRUNC(IMT.TRANSACTION_DATE, 'MM')

    --/Reportes Custom/SCM/PRO_EMBARQUES/Generales/XXGRG_SCM_HISTORY_REP.xdo
    --p_fecha_ini p_fecha_fin